In [27]:
import tensorflow as tf
import pathlib
import os
from datetime import datetime
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [2]:
x = tf.constant([[1,3,4],[5,7,8]])
print(x)

tf.Tensor(
[[1 3 4]
 [5 7 8]], shape=(2, 3), dtype=int32)


In [3]:
x+x



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  6,  8],
       [10, 14, 16]])>

In [4]:
5*x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 15, 20],
       [25, 35, 40]])>

In [5]:
tf.transpose(x)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [3, 7],
       [4, 8]])>

In [6]:
tf.concat([x,x,x],axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 3, 4],
       [5, 7, 8],
       [1, 3, 4],
       [5, 7, 8],
       [1, 3, 4],
       [5, 7, 8]])>

In [7]:
tf.nn.softmax(x, axis=-1)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: half, bfloat16, float, double
	; NodeDef: {{node Softmax}}; Op<name=Softmax; signature=logits:T -> softmax:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]> [Op:Softmax] name: 

In [ ]:
tf.reduce_sum(x)

In [ ]:
tf.convert_to_tensor([1,2,3])

In [ ]:
tf.reduce_sum([2,4,5])

In [ ]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

In [ ]:
var = tf.Variable([2335,2335,25446])

In [ ]:
var.assign([3,5,6,])
var

In [ ]:
var.assign_add([4,6,3])

In [ ]:
x = tf.Variable(1.0)
def f(x):
    y = x**2 + 2*x - 5
    return y

In [ ]:
x

In [ ]:
f(x)

In [ ]:
with tf.GradientTape() as tape:
    y= f(x)
g_x =tape.gradient(y,x)
g_x

In [ ]:
# graphs and tf.function

In [ ]:
tf.function
def my_func(x):
    print('Trancing.\n')
    return tf.reduce_sum(x)

In [ ]:
x

In [ ]:
x = tf.constant([4,5,3])
my_func(x)

In [ ]:
class Mymodule(tf.Module):
    def __init__(self, value):
        self.weight = tf.Variable(value)

    @tf.function
    def multiply(self,x):
        return x *self.weight

In [ ]:
mod = Mymodule(3)
mod.multiply(tf.constant([1,3,4]))

In [ ]:
# save the module

In [ ]:
save_path ='./saved'
tf.saved_model.save(mod, save_path)

In [ ]:
reloaded = tf.saved_model.load(save_path)
reloaded.multiply(tf.constant([2,4,5]))

In [44]:
class Simplemodule(tf.Module):
    def __init___(self, name = None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(4.0, name ="train_me")
        self.non_trainable_variable =tf.Variable(4, trainable= False , name="do_not_train_me")
    def __call__(self, x):
        return self.a_variable * x+self.non_trainable_variable

simple_module = SimpleModule(name="simple")

simple_module(tf.constant(4.0))
 

<tf.Tensor: shape=(), dtype=float32, numpy=25.0>

In [46]:
# All trainable variables
print("trainable variables:", simple_module.trainable_variables)
# Every variable
print("all variables:", simple_module.variables)

trainable variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
all variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)
